# docker compose file with mongodb self host
# docker compose -f docker-compose.yml -f docker-compose.db.yml up -d
# change base env DB_* env

services:
  shartube-mongo-db:
    container_name: shartube-mongo-db
    image: mongo
    networks:
      - shartube-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    depends_on:
      - shartube-ws-server
    restart: always
    volumes:
      - mongoDB:/data/db
    command: --quiet --logpath /dev/null