version: "3.6"

services:
  shartube-db:
    container_name: shartube-db
    image: mongo
    networks:
      - shartube-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    depends_on:
      - shartube-ws-server
    restart: always
    volumes:
      - mongoDB:/data/db
    command: --quiet --logpath /dev/null

  shartube-graphql-gateway:
    container_name: shartube-graphql-gateway
    networks:
      - shartube-net
    depends_on:
      - shartube-comic-server
      - shartube-user-server
    environment:
      - COMIC_SERVER_HOST=http://shartube-comic-server:8080/query
      - USER_SERVER_HOST=http://shartube-user-server:8080/graphql
    build: ./graphql-gateway
    env_file:
      - ./graphql-gateway/.env
      - ./.base.env
    restart: always

  shartube-ws-server:
    container_name: shartube-ws-server
    networks:
      - shartube-net
    build: ./socket
    restart: always
    expose:
      - 3012
    environment:
      - HOST=shartube-ws-server
    env_file:
      - ./.base.env

  shartube-comic-server:
    container_name: shartube-comic-server
    networks:
      - shartube-net
    depends_on:
      - shartube-db
      - shartube-user-server
    build: ./comic
    environment:
      - WS_HOST=shartube-ws-server
      - WS_PORT=3012
      - UserHost=shartube-user-server
      - UploadServer=http://shartube-upload-server:3000/save
    env_file:
      - ./comic/.env
      - ./.base.env
    restart: always
    expose:
      - 8080

  shartube-user-server:
    container_name: shartube-user-server
    networks:
      - shartube-net
    depends_on:
      - shartube-db
    build: ./user
    environment:
      - WS_HOST=shartube-ws-server
      - WS_PORT=3012
    env_file:
      - ./user/.env
      - ./.base.env
    restart: always
    expose:
      - 8080

  shartube-upload-server:
    container_name: shartube-upload-server
    networks:
      - shartube-net
    depends_on:
      - shartube-ws-server
    build: ./cdn-service
    env_file:
      - ./cdn-service/.env
      - ./.base.env
    restart: always
    expose:
      - 3000
    environment:
      - CHANNEL_ID=1043368131390885968
  
  shartube-api-gateway:
    container_name: shartube-api-gateway
    networks:
      - shartube-net
    depends_on:
      - shartube-graphql-gateway
    build: ./api-gateway
    env_file:
      - ./.base.env
    restart: always
    expose:
      - 8080
    environment:
      - PORT=8080
      - GRAPHQL_SERVER=http://shartube-graphql-gateway:2100
      - MEME_SERVER=http://shartube-meme-server:8080
    ports:
      - "8080:8080"
  
  shartube-meme-server:
    container_name: shartube-meme-server
    networks:
      - shartube-net
    depends_on:
      - shartube-db
    build: ./meme
    env_file:
      - ./.base.env
    restart: always
    expose:
      - 8080
    environment:
      - PORT=8080

networks:
  shartube-net:

volumes:
  mongoDB:
