[package]
name = "subtitle"
edition = "2021"
version = "0.0.1"

[dependencies]
actix-cors = "0.6.3"
actix-web = "4.2.1"
async-graphql = "4.0.13"
async-graphql-actix-web = "4.0.13"
mongodb = "2.3.0"
serde = "1.0.145"
